### PR TITLE
Add `tempel-define-template`

### PR DESCRIPTION
**Pull request by Luis-Henriquez-Perez**
This pull request is specifically for adding `tempel-define-template` and whatever changes are required to achieve this.

On the bare minimum, what `tempel-define-template` has to do (as I see it) is append a new element to `tempel--templates`. Its counterpart `tempo-define-template` does more--it creates an interactive function and a variable that corresponds to the template. But it is not clear to me how exactly that will be useful.

Something that needs to be changed for `tempel-define-template` is how templates are loaded currently. Right now, when you re-load template files, the templates are all overwritten. This is problematic for two reasons.

1. Loading does not usually work this way. Typically if you define, say, a function in a file and load it, then remove the function from the file, save the file and reload it, the function is still defined. Arguably, loading snippets should be the same way. Instead, we should append to the front of `tempel--templates` and additionally remove duplicate template definitions (by which I mean ones that have the same mode and name).

2. That would overwrite any templates defined by `tempel-define-template`.

### CODE REVIEW

**Comment by minad** [comment]
This needs more thought. See also #11.

**Comment by Luis-Henriquez-Perez** [comment]
> This needs more thought.

Ok. When you can please describe/list ideas what you have in mind. My goal with this minimal/basic `tempel-defined-template` is simply to "get the ball rolling" and provide something that we can work with and extend as more ideas are fleshed out.

**Comment by minad** [comment]
> My goal with this minimal/basic tempel-defined-template is simply to "get the ball rolling" and provide something that we can work with and extend as more ideas are fleshed out.

While I also do that occasionally, I prefer a development style where the feature is more fleshed out from the get go before I merge it.

> I'll also mention that I also really want this feature as I personally wouldn't like using a template file and would rather define them myself in my configuration.

Understood. We will add a facility to define templates from inside init files. But so far it looks as if you can implement the desired functionality with two lines of code in your init.el:

~~~ elisp
(defun tempel-define-template (trigger mode)
  (push (cons mode (cons trigger body)) tempel--templates))
~~~

I would like to address the multi file issue first #4, since this looks good and is an obvious generalization of the current functionality. Furthermore it makes sense to gather more feedback. @tpeacock19 is working on some templates. The more we know the easier it is to judge what to add and how to add it.

**Comment by Luis-Henriquez-Perez** [comment]
> But so far it looks as if you can implement the desired functionality with two lines of code in your init.el:

Oh ok. I had though that `tempel` would overwrite my evaluated templates if I set `tempel-file` to nil, but it looks like it wont from the test I did below.

```elisp
(let ((tempel-file nil)
      (tempel--templates '(1)))
  (let ((mod (file-attribute-modification-time (file-attributes tempel-file))))
    (unless (equal tempel--modified mod)
      (setq tempel--templates (tempel--load tempel-file)
	    tempel--modified mod)))
  tempel--templates)
;; => (1)
```
> While I also do that occasionally, I prefer a development style where the feature is more fleshed out from the get go before I merge it.

Ok. Fair enough.

>  I mean you can already start using Tempel as is, experiment with it, find edge cases, bugs and other improvement potential?

For sure. I've wanted a package like this for a long time. I plan to use this package *heavily* and to create many many snippets. I also want to investigate into making a `capf` for it so I can use it with `corfu`.

**Comment by minad** [comment]
> I also want to investigate into making a capf for it so I can use it with corfu.

`tempel-expand` is a capf.

**Comment by minad** [comment]
I added the possibility to define local templates in https://github.com/minad/tempel/commit/77868372482a3766bf41b902027ff6aa85739bf0. You can use this in your user configuration. Closing this for now. The question is if we need additional helper macros.

**Comment by Luis-Henriquez-Perez** [comment]
> added the possibility to define local templates in 7786837

Could you provide an example? I read over the diffs, but it seems a bit abstract to me. How does it compare in practice to `tempel-define-template` function you suggested? Or is `tempel-template-sources` meant to be used in combination with this function.

**Comment by minad** [comment]
Add your templates to tempel-local-templates.

**Pull request closed without merging**
