### PR TITLE
Implement fully configurable interpreter

### PR DESCRIPTION
**Pull request by minad**
Addresses #7 

Advantages:

* Fully configurable/hackable

Disadvantages:

* Complexity
* The templates which use a custom configuration cannot be shared easily

I am not entirely convinced by this since we already support arbitrary evaluated elements. If you want custom elements, write custom functions. We should not add this at all costs. Opinions? (cc @tpeacock19 @Luis-Henriquez-Perez)

### CODE REVIEW

**Comment by Luis-Henriquez-Perez** [comment]
> So the question is if we want to keep this [arbitrarily evaluated forms]. However custom user elements could be tried just before attempting evaluation.
> I am not entirely convinced by this since we already support arbitrary evaluated elements. If you want custom elements, write custom functions.

My idea on this is arbitrary lisp forms would be for "one-of" cases where you want to do something specific for the particular template. A custom function would be for the case where you do something for a template all the time. Whereas adding a template elements would be a more "advanced" case where you find what you believe to be a significant convenience/improvement to the template structure.

> We should not add this at all costs. Opinions? 

Perhaps we should take a "wait and see" approach. As this project matures, as we start actually writing more snippets, and as users start doing so, we see if a specific need arises where adding a new element would be useful.

**Comment by minad** [comment]
Agree. 

I realized there are two different approaches one could take here:

1. The fully configurable interpreter. This is probably overdoing it.
2. The original tempo approach where user elements are defined in terms of the primitive Tempo elements. The tempo-user-element functions must return an element or a list of elements themselves.

Maybe approach (2) is sufficient and even better since everything boils down to the original Tempo elements and one does not have to write these handlers which are implementation specific.

**Comment by tpeacock19** [comment]
> I am not entirely convinced by this since we already support arbitrary
evaluated elements.

> Perhaps we should take a "wait and see" approach.

I agree with both of you on this. Custom forms already exist and we'd be
creating a solution that users may not have need for.

**Comment by minad** [comment]
Okay, I don't want to go the way with the fully configurable interpreter. We can still consider adding some kind of support for user elements.

**Pull request closed without merging**
