### PR TITLE
Use :when as :enable-funcion in tempel-abbrev-mode

### PR DESCRIPTION
**Pull request by Ursus-GIT5805**
This is my feature request as discussed in #147.
Just let me know if there is something you don't like.

### CODE REVIEW

**Comment by minad** [comment]
I think we don't need the `:when`/`:enable-function` duplication. In the context of abbrev when should probably have the effect of an `:enable-function`?

Did you assign copyright to the FSF? I need your name to confirm, but you can also sent this to my in private via mail. See https://github.com/minad/tempel?tab=readme-ov-file#contributions.

**Comment by Ursus-GIT5805** [comment]
You're correct, using `:enable-function` is overly complicated.
I changed it so `:when` is also used for the abbrev-expansion.
For the copyright assignment, I sent you a mail.

**Comment by minad** [comment]
@Ursus-GIT5805 Has there been progress regarding the FSF assignment?

**Comment by Ursus-GIT5805** [comment]
I finally got the message that the deputy director will sign the contract (hopefully soon). We just have to have a little patience...

**Comment by Ursus-GIT5805** [comment]
Hey there,
The process is finally complete.

**Comment by minad** [comment]
Thanks. I tested this for a while and in the end I went with a simpler version: https://github.com/minad/tempel/commit/22f9348f1d8ebd6643929d427f4663b12fb5e239

One problem in your patch was that it changed the API of `tempel-template-sources`.

**Pull request merged**
